// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameRoom
    {
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "created_by_user_id")]
        public uint CreatedByUserId;
        [DataMember(Name = "creator_identity")]
        public SpacetimeDB.Identity CreatorIdentity;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "password")]
        public string Password;

        public GameRoom(
            uint RoomId,
            string Name,
            uint CreatedByUserId,
            SpacetimeDB.Identity CreatorIdentity,
            ulong CreatedAt,
            string Password
        )
        {
            this.RoomId = RoomId;
            this.Name = Name;
            this.CreatedByUserId = CreatedByUserId;
            this.CreatorIdentity = CreatorIdentity;
            this.CreatedAt = CreatedAt;
            this.Password = Password;
        }

        public GameRoom()
        {
            this.Name = "";
            this.Password = "";
        }
    }
}
