// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameRoom
    {
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "name")]
        public string Name;

        public GameRoom(
            uint RoomId,
            string Name
        )
        {
            this.RoomId = RoomId;
            this.Name = Name;
        }

        public GameRoom()
        {
            this.Name = "";
        }
    }
}
