// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameRoomSecret
    {
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "password")]
        public string Password;

        public GameRoomSecret(
            uint RoomId,
            string Password
        )
        {
            this.RoomId = RoomId;
            this.Password = Password;
        }

        public GameRoomSecret()
        {
            this.Password = "";
        }
    }
}
