// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Images
    {
        [DataMember(Name = "building_identifier")]
        public string BuildingIdentifier;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "width")]
        public int Width;
        [DataMember(Name = "height")]
        public int Height;
        [DataMember(Name = "image_data")]
        public System.Collections.Generic.List<byte> ImageData;

        public Images(
            string BuildingIdentifier,
            uint RoomId,
            ulong Timestamp,
            SpacetimeDB.Identity Sender,
            int Width,
            int Height,
            System.Collections.Generic.List<byte> ImageData
        )
        {
            this.BuildingIdentifier = BuildingIdentifier;
            this.RoomId = RoomId;
            this.Timestamp = Timestamp;
            this.Sender = Sender;
            this.Width = Width;
            this.Height = Height;
            this.ImageData = ImageData;
        }

        public Images()
        {
            this.BuildingIdentifier = "";
            this.ImageData = new();
        }
    }
}
