// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ImageBroadcastLock
    {
        [DataMember(Name = "building_identifier")]
        public string BuildingIdentifier;
        [DataMember(Name = "sender_user_id")]
        public uint SenderUserId;
        [DataMember(Name = "sender_username")]
        public string SenderUsername;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public ImageBroadcastLock(
            string BuildingIdentifier,
            uint SenderUserId,
            string SenderUsername,
            ulong Timestamp
        )
        {
            this.BuildingIdentifier = BuildingIdentifier;
            this.SenderUserId = SenderUserId;
            this.SenderUsername = SenderUsername;
            this.Timestamp = Timestamp;
        }

        public ImageBroadcastLock()
        {
            this.BuildingIdentifier = "";
            this.SenderUsername = "";
        }
    }
}
