// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ImageBroadcastLock
    {
        [DataMember(Name = "building_identifier")]
        public string BuildingIdentifier;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public ImageBroadcastLock(
            string BuildingIdentifier,
            SpacetimeDB.Identity Sender,
            ulong Timestamp
        )
        {
            this.BuildingIdentifier = BuildingIdentifier;
            this.Sender = Sender;
            this.Timestamp = Timestamp;
        }

        public ImageBroadcastLock()
        {
            this.BuildingIdentifier = "";
        }
    }
}
