// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ImageBroadcastLock
    {
        [DataMember(Name = "image_id")]
        public uint ImageId;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public ImageBroadcastLock(
            uint ImageId,
            SpacetimeDB.Identity Sender,
            ulong Timestamp
        )
        {
            this.ImageId = ImageId;
            this.Sender = Sender;
            this.Timestamp = Timestamp;
        }

        public ImageBroadcastLock()
        {
        }
    }
}
