// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Images
    {
        [DataMember(Name = "image_id")]
        public uint ImageId;
        [DataMember(Name = "building_identifier")]
        public string BuildingIdentifier;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "image_data")]
        public System.Collections.Generic.List<byte> ImageData;

        public Images(
            uint ImageId,
            string BuildingIdentifier,
            uint RoomId,
            System.Collections.Generic.List<byte> ImageData
        )
        {
            this.ImageId = ImageId;
            this.BuildingIdentifier = BuildingIdentifier;
            this.RoomId = RoomId;
            this.ImageData = ImageData;
        }

        public Images()
        {
            this.BuildingIdentifier = "";
            this.ImageData = new();
        }
    }
}
