// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedOutPlayer
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "color")]
        public string Color;
        [DataMember(Name = "last_disconnect_time")]
        public ulong LastDisconnectTime;
        [DataMember(Name = "total_play_time")]
        public ulong TotalPlayTime;

        public LoggedOutPlayer(
            SpacetimeDB.Identity Identity,
            uint PlayerId,
            string Name,
            string Color,
            ulong LastDisconnectTime,
            ulong TotalPlayTime
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.Color = Color;
            this.LastDisconnectTime = LastDisconnectTime;
            this.TotalPlayTime = TotalPlayTime;
        }

        public LoggedOutPlayer()
        {
            this.Name = "";
            this.Color = "";
        }
    }
}
