// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedOutPlayer
    {
        [DataMember(Name = "user_id")]
        public uint UserId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "color")]
        public string Color;
        [DataMember(Name = "last_disconnect_time")]
        public ulong LastDisconnectTime;
        [DataMember(Name = "total_play_time")]
        public ulong TotalPlayTime;

        public LoggedOutPlayer(
            uint UserId,
            string Username,
            string Color,
            ulong LastDisconnectTime,
            ulong TotalPlayTime
        )
        {
            this.UserId = UserId;
            this.Username = Username;
            this.Color = Color;
            this.LastDisconnectTime = LastDisconnectTime;
            this.TotalPlayTime = TotalPlayTime;
        }

        public LoggedOutPlayer()
        {
            this.Username = "";
            this.Color = "";
        }
    }
}
