// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedOutPlayer
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "color")]
        public string Color;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "last_position")]
        public DbVector3 LastPosition;

        public LoggedOutPlayer(
            SpacetimeDB.Identity Identity,
            uint PlayerId,
            string Name,
            string Color,
            uint RoomId,
            DbVector3 LastPosition
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.Color = Color;
            this.RoomId = RoomId;
            this.LastPosition = LastPosition;
        }

        public LoggedOutPlayer()
        {
            this.Name = "";
            this.Color = "";
            this.LastPosition = new();
        }
    }
}
