// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OnlinePlayer
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "color")]
        public string Color;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "last_room_join_time")]
        public ulong LastRoomJoinTime;
        [DataMember(Name = "last_connect_time")]
        public ulong LastConnectTime;
        [DataMember(Name = "total_play_time")]
        public ulong TotalPlayTime;
        [DataMember(Name = "last_position")]
        public DbVector3 LastPosition;
        [DataMember(Name = "last_rotation")]
        public float LastRotation;

        public OnlinePlayer(
            SpacetimeDB.Identity Identity,
            uint PlayerId,
            string Name,
            string Color,
            uint RoomId,
            ulong LastRoomJoinTime,
            ulong LastConnectTime,
            ulong TotalPlayTime,
            DbVector3 LastPosition,
            float LastRotation
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.Color = Color;
            this.RoomId = RoomId;
            this.LastRoomJoinTime = LastRoomJoinTime;
            this.LastConnectTime = LastConnectTime;
            this.TotalPlayTime = TotalPlayTime;
            this.LastPosition = LastPosition;
            this.LastRotation = LastRotation;
        }

        public OnlinePlayer()
        {
            this.Name = "";
            this.Color = "";
            this.LastPosition = new();
        }
    }
}
