// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerRoomPosition
    {
        [DataMember(Name = "identity_room_key")]
        public string IdentityRoomKey;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "last_position")]
        public DbVector3 LastPosition;
        [DataMember(Name = "last_rotation")]
        public float LastRotation;

        public PlayerRoomPosition(
            string IdentityRoomKey,
            SpacetimeDB.Identity Identity,
            uint RoomId,
            DbVector3 LastPosition,
            float LastRotation
        )
        {
            this.IdentityRoomKey = IdentityRoomKey;
            this.Identity = Identity;
            this.RoomId = RoomId;
            this.LastPosition = LastPosition;
            this.LastRotation = LastRotation;
        }

        public PlayerRoomPosition()
        {
            this.IdentityRoomKey = "";
            this.LastPosition = new();
        }
    }
}
