// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerCount
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "count")]
        public uint Count;

        public PlayerCount(
            uint Id,
            uint Count
        )
        {
            this.Id = Id;
            this.Count = Count;
        }

        public PlayerCount()
        {
        }
    }
}
