// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerRoomPosition
    {
        [DataMember(Name = "user_room_key")]
        public string UserRoomKey;
        [DataMember(Name = "user_id")]
        public uint UserId;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "last_position")]
        public DbVector3 LastPosition;
        [DataMember(Name = "last_rotation")]
        public float LastRotation;
        [DataMember(Name = "last_updated")]
        public ulong LastUpdated;

        public PlayerRoomPosition(
            string UserRoomKey,
            uint UserId,
            uint RoomId,
            DbVector3 LastPosition,
            float LastRotation,
            ulong LastUpdated
        )
        {
            this.UserRoomKey = UserRoomKey;
            this.UserId = UserId;
            this.RoomId = RoomId;
            this.LastPosition = LastPosition;
            this.LastRotation = LastRotation;
            this.LastUpdated = LastUpdated;
        }

        public PlayerRoomPosition()
        {
            this.UserRoomKey = "";
            this.LastPosition = new();
        }
    }
}
