// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomEntity
    {
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "data")]
        public string Data;

        public RoomEntity(
            uint RoomId,
            SpacetimeDB.Identity Identity,
            string Data
        )
        {
            this.RoomId = RoomId;
            this.Identity = Identity;
            this.Data = Data;
        }

        public RoomEntity()
        {
            this.Data = "";
        }
    }
}
