// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomSessionHistory
    {
        [DataMember(Name = "session_id")]
        public uint SessionId;
        [DataMember(Name = "user_id")]
        public uint UserId;
        [DataMember(Name = "user_name")]
        public string UserName;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "entry_time")]
        public ulong EntryTime;
        [DataMember(Name = "exit_time")]
        public ulong ExitTime;
        [DataMember(Name = "duration_microseconds")]
        public ulong DurationMicroseconds;

        public RoomSessionHistory(
            uint SessionId,
            uint UserId,
            string UserName,
            uint RoomId,
            ulong EntryTime,
            ulong ExitTime,
            ulong DurationMicroseconds
        )
        {
            this.SessionId = SessionId;
            this.UserId = UserId;
            this.UserName = UserName;
            this.RoomId = RoomId;
            this.EntryTime = EntryTime;
            this.ExitTime = ExitTime;
            this.DurationMicroseconds = DurationMicroseconds;
        }

        public RoomSessionHistory()
        {
            this.UserName = "";
        }
    }
}
