// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomEntity
    {
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "user_id")]
        public uint UserId;
        [DataMember(Name = "data")]
        public string Data;
        [DataMember(Name = "last_updated")]
        public ulong LastUpdated;

        public RoomEntity(
            uint RoomId,
            uint UserId,
            string Data,
            ulong LastUpdated
        )
        {
            this.RoomId = RoomId;
            this.UserId = UserId;
            this.Data = Data;
            this.LastUpdated = LastUpdated;
        }

        public RoomEntity()
        {
            this.Data = "";
        }
    }
}
