// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoomEntity
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "room_id")]
        public uint RoomId;
        [DataMember(Name = "prefab_id")]
        public string PrefabId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;
        [DataMember(Name = "scale")]
        public DbVector3 Scale;

        public RoomEntity(
            uint EntityId,
            uint RoomId,
            string PrefabId,
            DbVector3 Position,
            DbVector3 Rotation,
            DbVector3 Scale
        )
        {
            this.EntityId = EntityId;
            this.RoomId = RoomId;
            this.PrefabId = PrefabId;
            this.Position = Position;
            this.Rotation = Rotation;
            this.Scale = Scale;
        }

        public RoomEntity()
        {
            this.PrefabId = "";
            this.Position = new();
            this.Rotation = new();
            this.Scale = new();
        }
    }
}
