// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserSession
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "user_id")]
        public uint UserId;
        [DataMember(Name = "created_at")]
        public ulong CreatedAt;
        [DataMember(Name = "last_activity")]
        public ulong LastActivity;

        public UserSession(
            SpacetimeDB.Identity Identity,
            uint UserId,
            ulong CreatedAt,
            ulong LastActivity
        )
        {
            this.Identity = Identity;
            this.UserId = UserId;
            this.CreatedAt = CreatedAt;
            this.LastActivity = LastActivity;
        }

        public UserSession()
        {
        }
    }
}
