// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatMessageHandle : RemoteTableHandle<EventContext, ChatMessage>
        {
            protected override string RemoteTableName => "chat_message";

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ChatMessage row) => row.MessageId;

                public MessageIdUniqueIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            public sealed class RoomIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ChatMessage row) => row.RoomId;

                public RoomIdIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal ChatMessageHandle(DbConnection conn) : base(conn)
            {
                MessageId = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(ChatMessage row) => row.MessageId;
        }

        public readonly ChatMessageHandle ChatMessage;
    }
}
