// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameRoomHandle : RemoteTableHandle<EventContext, GameRoom>
        {
            protected override string RemoteTableName => "game_room";

            public sealed class RoomIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameRoom row) => row.RoomId;

                public RoomIdUniqueIndex(GameRoomHandle table) : base(table) { }
            }

            public readonly RoomIdUniqueIndex RoomId;

            internal GameRoomHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(GameRoom row) => row.RoomId;
        }

        public readonly GameRoomHandle GameRoom;
    }
}
