// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameRoomSecretHandle : RemoteTableHandle<EventContext, GameRoomSecret>
        {
            protected override string RemoteTableName => "game_room_secret";

            public sealed class RoomIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameRoomSecret row) => row.RoomId;

                public RoomIdUniqueIndex(GameRoomSecretHandle table) : base(table) { }
            }

            public readonly RoomIdUniqueIndex RoomId;

            internal GameRoomSecretHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(GameRoomSecret row) => row.RoomId;
        }

        public readonly GameRoomSecretHandle GameRoomSecret;
    }
}
