// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ImagesHandle : RemoteTableHandle<EventContext, Images>
        {
            protected override string RemoteTableName => "images";

            public sealed class BuildingIdentifierUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Images row) => row.BuildingIdentifier;

                public BuildingIdentifierUniqueIndex(ImagesHandle table) : base(table) { }
            }

            public readonly BuildingIdentifierUniqueIndex BuildingIdentifier;

            public sealed class RoomIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Images row) => row.RoomId;

                public RoomIdIndex(ImagesHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal ImagesHandle(DbConnection conn) : base(conn)
            {
                BuildingIdentifier = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(Images row) => row.BuildingIdentifier;
        }

        public readonly ImagesHandle Images;
    }
}
