// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ImageBroadcastLockHandle : RemoteTableHandle<EventContext, ImageBroadcastLock>
        {
            protected override string RemoteTableName => "image_broadcast_lock";

            public sealed class ImageIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ImageBroadcastLock row) => row.ImageId;

                public ImageIdUniqueIndex(ImageBroadcastLockHandle table) : base(table) { }
            }

            public readonly ImageIdUniqueIndex ImageId;

            internal ImageBroadcastLockHandle(DbConnection conn) : base(conn)
            {
                ImageId = new(this);
            }
        }

        public readonly ImageBroadcastLockHandle ImageBroadcastLock;
    }
}
