// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ImageBroadcastLockHandle : RemoteTableHandle<EventContext, ImageBroadcastLock>
        {
            protected override string RemoteTableName => "image_broadcast_lock";

            public sealed class BuildingIdentifierUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ImageBroadcastLock row) => row.BuildingIdentifier;

                public BuildingIdentifierUniqueIndex(ImageBroadcastLockHandle table) : base(table) { }
            }

            public readonly BuildingIdentifierUniqueIndex BuildingIdentifier;

            public sealed class SenderUserIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ImageBroadcastLock row) => row.SenderUserId;

                public SenderUserIdIndex(ImageBroadcastLockHandle table) : base(table) { }
            }

            public readonly SenderUserIdIndex SenderUserId;

            internal ImageBroadcastLockHandle(DbConnection conn) : base(conn)
            {
                BuildingIdentifier = new(this);
                SenderUserId = new(this);
            }

            protected override object GetPrimaryKey(ImageBroadcastLock row) => row.BuildingIdentifier;
        }

        public readonly ImageBroadcastLockHandle ImageBroadcastLock;
    }
}
