// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LoggedOutPlayerHandle : RemoteTableHandle<EventContext, LoggedOutPlayer>
        {
            protected override string RemoteTableName => "logged_out_player";

            public sealed class UserIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(LoggedOutPlayer row) => row.UserId;

                public UserIdUniqueIndex(LoggedOutPlayerHandle table) : base(table) { }
            }

            public readonly UserIdUniqueIndex UserId;

            internal LoggedOutPlayerHandle(DbConnection conn) : base(conn)
            {
                UserId = new(this);
            }

            protected override object GetPrimaryKey(LoggedOutPlayer row) => row.UserId;
        }

        public readonly LoggedOutPlayerHandle LoggedOutPlayer;
    }
}
