// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OnlinePlayerHandle : RemoteTableHandle<EventContext, OnlinePlayer>
        {
            protected override string RemoteTableName => "online_player";

            public sealed class RoomIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(OnlinePlayer row) => row.RoomId;

                public RoomIdIndex(OnlinePlayerHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            public sealed class UserIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(OnlinePlayer row) => row.UserId;

                public UserIdUniqueIndex(OnlinePlayerHandle table) : base(table) { }
            }

            public readonly UserIdUniqueIndex UserId;

            internal OnlinePlayerHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
                UserId = new(this);
            }

            protected override object GetPrimaryKey(OnlinePlayer row) => row.UserId;
        }

        public readonly OnlinePlayerHandle OnlinePlayer;
    }
}
