// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OnlinePlayerHandle : RemoteTableHandle<EventContext, OnlinePlayer>
        {
            protected override string RemoteTableName => "online_player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(OnlinePlayer row) => row.Identity;

                public IdentityUniqueIndex(OnlinePlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(OnlinePlayer row) => row.PlayerId;

                public PlayerIdUniqueIndex(OnlinePlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            public sealed class RoomIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(OnlinePlayer row) => row.RoomId;

                public RoomIdIndex(OnlinePlayerHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal OnlinePlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                PlayerId = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(OnlinePlayer row) => row.Identity;
        }

        public readonly OnlinePlayerHandle OnlinePlayer;
    }
}
