// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerRoomPositionHandle : RemoteTableHandle<EventContext, PlayerRoomPosition>
        {
            protected override string RemoteTableName => "player_room_position";

            public sealed class IdentityRoomKeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PlayerRoomPosition row) => row.IdentityRoomKey;

                public IdentityRoomKeyUniqueIndex(PlayerRoomPositionHandle table) : base(table) { }
            }

            public readonly IdentityRoomKeyUniqueIndex IdentityRoomKey;

            internal PlayerRoomPositionHandle(DbConnection conn) : base(conn)
            {
                IdentityRoomKey = new(this);
            }

            protected override object GetPrimaryKey(PlayerRoomPosition row) => row.IdentityRoomKey;
        }

        public readonly PlayerRoomPositionHandle PlayerRoomPosition;
    }
}
