// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomEntityHandle : RemoteTableHandle<EventContext, RoomEntity>
        {
            protected override string RemoteTableName => "room_entity";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(RoomEntity row) => row.EntityId;

                public EntityIdUniqueIndex(RoomEntityHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class RoomIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(RoomEntity row) => row.RoomId;

                public RoomIdIndex(RoomEntityHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            internal RoomEntityHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomEntity row) => row.EntityId;
        }

        public readonly RoomEntityHandle RoomEntity;
    }
}
