// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomEntityHandle : RemoteTableHandle<EventContext, RoomEntity>
        {
            protected override string RemoteTableName => "room_entity";

            public sealed class RoomIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(RoomEntity row) => row.RoomId;

                public RoomIdUniqueIndex(RoomEntityHandle table) : base(table) { }
            }

            public readonly RoomIdUniqueIndex RoomId;

            internal RoomEntityHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
            }

            protected override object GetPrimaryKey(RoomEntity row) => row.RoomId;
        }

        public readonly RoomEntityHandle RoomEntity;
    }
}
