// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoomSessionHistoryHandle : RemoteTableHandle<EventContext, RoomSessionHistory>
        {
            protected override string RemoteTableName => "room_session_history";

            public sealed class RoomIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(RoomSessionHistory row) => row.RoomId;

                public RoomIdIndex(RoomSessionHistoryHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            public sealed class SessionIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(RoomSessionHistory row) => row.SessionId;

                public SessionIdUniqueIndex(RoomSessionHistoryHandle table) : base(table) { }
            }

            public readonly SessionIdUniqueIndex SessionId;

            internal RoomSessionHistoryHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(RoomSessionHistory row) => row.SessionId;
        }

        public readonly RoomSessionHistoryHandle RoomSessionHistory;
    }
}
