// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VoiceClipHandle : RemoteTableHandle<EventContext, VoiceClip>
        {
            protected override string RemoteTableName => "voice_clip";

            public sealed class RoomIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(VoiceClip row) => row.RoomId;

                public RoomIdIndex(VoiceClipHandle table) : base(table) { }
            }

            public readonly RoomIdIndex RoomId;

            public sealed class SenderUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(VoiceClip row) => row.Sender;

                public SenderUniqueIndex(VoiceClipHandle table) : base(table) { }
            }

            public readonly SenderUniqueIndex Sender;

            internal VoiceClipHandle(DbConnection conn) : base(conn)
            {
                RoomId = new(this);
                Sender = new(this);
            }

            protected override object GetPrimaryKey(VoiceClip row) => row.Sender;
        }

        public readonly VoiceClipHandle VoiceClip;
    }
}
