// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateRoomHandler(ReducerEventContext ctx, string roomName, string password);
        public event CreateRoomHandler? OnCreateRoom;

        public void CreateRoom(string roomName, string password)
        {
            conn.InternalCallReducer(new Reducer.CreateRoom(roomName, password), this.SetCallReducerFlags.CreateRoomFlags);
        }

        public bool InvokeCreateRoom(ReducerEventContext ctx, Reducer.CreateRoom args)
        {
            if (OnCreateRoom == null) return false;
            OnCreateRoom(
                ctx,
                args.RoomName,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateRoom : Reducer, IReducerArgs
        {
            [DataMember(Name = "room_name")]
            public string RoomName;
            [DataMember(Name = "password")]
            public string Password;

            public CreateRoom(
                string RoomName,
                string Password
            )
            {
                this.RoomName = RoomName;
                this.Password = Password;
            }

            public CreateRoom()
            {
                this.RoomName = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "CreateRoom";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateRoomFlags;
        public void CreateRoom(CallReducerFlags flags) => CreateRoomFlags = flags;
    }
}
