// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateOnlinePlayerHandler(ReducerEventContext ctx);
        public event CreateOnlinePlayerHandler? OnCreateOnlinePlayer;

        public void CreateOnlinePlayer()
        {
            conn.InternalCallReducer(new Reducer.CreateOnlinePlayer(), this.SetCallReducerFlags.CreateOnlinePlayerFlags);
        }

        public bool InvokeCreateOnlinePlayer(ReducerEventContext ctx, Reducer.CreateOnlinePlayer args)
        {
            if (OnCreateOnlinePlayer == null) return false;
            OnCreateOnlinePlayer(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateOnlinePlayer : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "CreateOnlinePlayer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateOnlinePlayerFlags;
        public void CreateOnlinePlayer(CallReducerFlags flags) => CreateOnlinePlayerFlags = flags;
    }
}
