// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GetCurrentTimeHandler(ReducerEventContext ctx);
        public event GetCurrentTimeHandler? OnGetCurrentTime;

        public void GetCurrentTime()
        {
            conn.InternalCallReducer(new Reducer.GetCurrentTime(), this.SetCallReducerFlags.GetCurrentTimeFlags);
        }

        public bool InvokeGetCurrentTime(ReducerEventContext ctx, Reducer.GetCurrentTime args)
        {
            if (OnGetCurrentTime == null) return false;
            OnGetCurrentTime(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GetCurrentTime : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "GetCurrentTime";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GetCurrentTimeFlags;
        public void GetCurrentTime(CallReducerFlags flags) => GetCurrentTimeFlags = flags;
    }
}
