// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinRoomHandler(ReducerEventContext ctx, string roomName, string password);
        public event JoinRoomHandler? OnJoinRoom;

        public void JoinRoom(string roomName, string password)
        {
            conn.InternalCallReducer(new Reducer.JoinRoom(roomName, password), this.SetCallReducerFlags.JoinRoomFlags);
        }

        public bool InvokeJoinRoom(ReducerEventContext ctx, Reducer.JoinRoom args)
        {
            if (OnJoinRoom == null) return false;
            OnJoinRoom(
                ctx,
                args.RoomName,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinRoom : Reducer, IReducerArgs
        {
            [DataMember(Name = "room_name")]
            public string RoomName;
            [DataMember(Name = "password")]
            public string Password;

            public JoinRoom(
                string RoomName,
                string Password
            )
            {
                this.RoomName = RoomName;
                this.Password = Password;
            }

            public JoinRoom()
            {
                this.RoomName = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "JoinRoom";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags JoinRoomFlags;
        public void JoinRoom(CallReducerFlags flags) => JoinRoomFlags = flags;
    }
}
