// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LockImageBroadcastHandler(ReducerEventContext ctx, string buildingIdentifier);
        public event LockImageBroadcastHandler? OnLockImageBroadcast;

        public void LockImageBroadcast(string buildingIdentifier)
        {
            conn.InternalCallReducer(new Reducer.LockImageBroadcast(buildingIdentifier), this.SetCallReducerFlags.LockImageBroadcastFlags);
        }

        public bool InvokeLockImageBroadcast(ReducerEventContext ctx, Reducer.LockImageBroadcast args)
        {
            if (OnLockImageBroadcast == null) return false;
            OnLockImageBroadcast(
                ctx,
                args.BuildingIdentifier
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LockImageBroadcast : Reducer, IReducerArgs
        {
            [DataMember(Name = "building_identifier")]
            public string BuildingIdentifier;

            public LockImageBroadcast(string BuildingIdentifier)
            {
                this.BuildingIdentifier = BuildingIdentifier;
            }

            public LockImageBroadcast()
            {
                this.BuildingIdentifier = "";
            }

            string IReducerArgs.ReducerName => "LockImageBroadcast";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LockImageBroadcastFlags;
        public void LockImageBroadcast(CallReducerFlags flags) => LockImageBroadcastFlags = flags;
    }
}
