// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LoginHandler(ReducerEventContext ctx, string email, string password);
        public event LoginHandler? OnLogin;

        public void Login(string email, string password)
        {
            conn.InternalCallReducer(new Reducer.Login(email, password), this.SetCallReducerFlags.LoginFlags);
        }

        public bool InvokeLogin(ReducerEventContext ctx, Reducer.Login args)
        {
            if (OnLogin == null) return false;
            OnLogin(
                ctx,
                args.Email,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Login : Reducer, IReducerArgs
        {
            [DataMember(Name = "email")]
            public string Email;
            [DataMember(Name = "password")]
            public string Password;

            public Login(
                string Email,
                string Password
            )
            {
                this.Email = Email;
                this.Password = Password;
            }

            public Login()
            {
                this.Email = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "Login";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LoginFlags;
        public void Login(CallReducerFlags flags) => LoginFlags = flags;
    }
}
