// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveEntityHandler(ReducerEventContext ctx, uint entityId);
        public event RemoveEntityHandler? OnRemoveEntity;

        public void RemoveEntity(uint entityId)
        {
            conn.InternalCallReducer(new Reducer.RemoveEntity(entityId), this.SetCallReducerFlags.RemoveEntityFlags);
        }

        public bool InvokeRemoveEntity(ReducerEventContext ctx, Reducer.RemoveEntity args)
        {
            if (OnRemoveEntity == null) return false;
            OnRemoveEntity(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public uint EntityId;

            public RemoveEntity(uint EntityId)
            {
                this.EntityId = EntityId;
            }

            public RemoveEntity()
            {
            }

            string IReducerArgs.ReducerName => "RemoveEntity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RemoveEntityFlags;
        public void RemoveEntity(CallReducerFlags flags) => RemoveEntityFlags = flags;
    }
}
