// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SaveEntityHandler(ReducerEventContext ctx, uint roomId, string data);
        public event SaveEntityHandler? OnSaveEntity;

        public void SaveEntity(uint roomId, string data)
        {
            conn.InternalCallReducer(new Reducer.SaveEntity(roomId, data), this.SetCallReducerFlags.SaveEntityFlags);
        }

        public bool InvokeSaveEntity(ReducerEventContext ctx, Reducer.SaveEntity args)
        {
            if (OnSaveEntity == null) return false;
            OnSaveEntity(
                ctx,
                args.RoomId,
                args.Data
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SaveEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "room_id")]
            public uint RoomId;
            [DataMember(Name = "data")]
            public string Data;

            public SaveEntity(
                uint RoomId,
                string Data
            )
            {
                this.RoomId = RoomId;
                this.Data = Data;
            }

            public SaveEntity()
            {
                this.Data = "";
            }

            string IReducerArgs.ReducerName => "SaveEntity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SaveEntityFlags;
        public void SaveEntity(CallReducerFlags flags) => SaveEntityFlags = flags;
    }
}
