// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendMessageHandler(ReducerEventContext ctx, string content, bool shout);
        public event SendMessageHandler? OnSendMessage;

        public void SendMessage(string content, bool shout)
        {
            conn.InternalCallReducer(new Reducer.SendMessage(content, shout), this.SetCallReducerFlags.SendMessageFlags);
        }

        public bool InvokeSendMessage(ReducerEventContext ctx, Reducer.SendMessage args)
        {
            if (OnSendMessage == null) return false;
            OnSendMessage(
                ctx,
                args.Content,
                args.Shout
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "content")]
            public string Content;
            [DataMember(Name = "shout")]
            public bool Shout;

            public SendMessage(
                string Content,
                bool Shout
            )
            {
                this.Content = Content;
                this.Shout = Shout;
            }

            public SendMessage()
            {
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "SendMessage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendMessageFlags;
        public void SendMessage(CallReducerFlags flags) => SendMessageFlags = flags;
    }
}
