// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendImageHandler(ReducerEventContext ctx, string buildingIdentifier, System.Collections.Generic.List<byte> imageData, int width, int height);
        public event SendImageHandler? OnSendImage;

        public void SendImage(string buildingIdentifier, System.Collections.Generic.List<byte> imageData, int width, int height)
        {
            conn.InternalCallReducer(new Reducer.SendImage(buildingIdentifier, imageData, width, height), this.SetCallReducerFlags.SendImageFlags);
        }

        public bool InvokeSendImage(ReducerEventContext ctx, Reducer.SendImage args)
        {
            if (OnSendImage == null) return false;
            OnSendImage(
                ctx,
                args.BuildingIdentifier,
                args.ImageData,
                args.Width,
                args.Height
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendImage : Reducer, IReducerArgs
        {
            [DataMember(Name = "building_identifier")]
            public string BuildingIdentifier;
            [DataMember(Name = "image_data")]
            public System.Collections.Generic.List<byte> ImageData;
            [DataMember(Name = "width")]
            public int Width;
            [DataMember(Name = "height")]
            public int Height;

            public SendImage(
                string BuildingIdentifier,
                System.Collections.Generic.List<byte> ImageData,
                int Width,
                int Height
            )
            {
                this.BuildingIdentifier = BuildingIdentifier;
                this.ImageData = ImageData;
                this.Width = Width;
                this.Height = Height;
            }

            public SendImage()
            {
                this.BuildingIdentifier = "";
                this.ImageData = new();
            }

            string IReducerArgs.ReducerName => "SendImage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendImageFlags;
        public void SendImage(CallReducerFlags flags) => SendImageFlags = flags;
    }
}
