// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendVoiceHandler(ReducerEventContext ctx, uint roomId, System.Collections.Generic.List<byte> audioData);
        public event SendVoiceHandler? OnSendVoice;

        public void SendVoice(uint roomId, System.Collections.Generic.List<byte> audioData)
        {
            conn.InternalCallReducer(new Reducer.SendVoice(roomId, audioData), this.SetCallReducerFlags.SendVoiceFlags);
        }

        public bool InvokeSendVoice(ReducerEventContext ctx, Reducer.SendVoice args)
        {
            if (OnSendVoice == null) return false;
            OnSendVoice(
                ctx,
                args.RoomId,
                args.AudioData
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendVoice : Reducer, IReducerArgs
        {
            [DataMember(Name = "room_id")]
            public uint RoomId;
            [DataMember(Name = "audio_data")]
            public System.Collections.Generic.List<byte> AudioData;

            public SendVoice(
                uint RoomId,
                System.Collections.Generic.List<byte> AudioData
            )
            {
                this.RoomId = RoomId;
                this.AudioData = AudioData;
            }

            public SendVoice()
            {
                this.AudioData = new();
            }

            string IReducerArgs.ReducerName => "SendVoice";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SendVoiceFlags;
        public void SendVoice(CallReducerFlags flags) => SendVoiceFlags = flags;
    }
}
