// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPlayerUsernameHandler(ReducerEventContext ctx, string username);
        public event SetPlayerUsernameHandler? OnSetPlayerUsername;

        public void SetPlayerUsername(string username)
        {
            conn.InternalCallReducer(new Reducer.SetPlayerUsername(username), this.SetCallReducerFlags.SetPlayerUsernameFlags);
        }

        public bool InvokeSetPlayerUsername(ReducerEventContext ctx, Reducer.SetPlayerUsername args)
        {
            if (OnSetPlayerUsername == null) return false;
            OnSetPlayerUsername(
                ctx,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPlayerUsername : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;

            public SetPlayerUsername(string Username)
            {
                this.Username = Username;
            }

            public SetPlayerUsername()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "SetPlayerUsername";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetPlayerUsernameFlags;
        public void SetPlayerUsername(CallReducerFlags flags) => SetPlayerUsernameFlags = flags;
    }
}
