// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPlayerColorHandler(ReducerEventContext ctx, string color);
        public event SetPlayerColorHandler? OnSetPlayerColor;

        public void SetPlayerColor(string color)
        {
            conn.InternalCallReducer(new Reducer.SetPlayerColor(color), this.SetCallReducerFlags.SetPlayerColorFlags);
        }

        public bool InvokeSetPlayerColor(ReducerEventContext ctx, Reducer.SetPlayerColor args)
        {
            if (OnSetPlayerColor == null) return false;
            OnSetPlayerColor(
                ctx,
                args.Color
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPlayerColor : Reducer, IReducerArgs
        {
            [DataMember(Name = "color")]
            public string Color;

            public SetPlayerColor(string Color)
            {
                this.Color = Color;
            }

            public SetPlayerColor()
            {
                this.Color = "";
            }

            string IReducerArgs.ReducerName => "SetPlayerColor";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetPlayerColorFlags;
        public void SetPlayerColor(CallReducerFlags flags) => SetPlayerColorFlags = flags;
    }
}
