// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPlayerProfileHandler(ReducerEventContext ctx, string name, string color);
        public event SetPlayerProfileHandler? OnSetPlayerProfile;

        public void SetPlayerProfile(string name, string color)
        {
            conn.InternalCallReducer(new Reducer.SetPlayerProfile(name, color), this.SetCallReducerFlags.SetPlayerProfileFlags);
        }

        public bool InvokeSetPlayerProfile(ReducerEventContext ctx, Reducer.SetPlayerProfile args)
        {
            if (OnSetPlayerProfile == null) return false;
            OnSetPlayerProfile(
                ctx,
                args.Name,
                args.Color
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPlayerProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "color")]
            public string Color;

            public SetPlayerProfile(
                string Name,
                string Color
            )
            {
                this.Name = Name;
                this.Color = Color;
            }

            public SetPlayerProfile()
            {
                this.Name = "";
                this.Color = "";
            }

            string IReducerArgs.ReducerName => "SetPlayerProfile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetPlayerProfileFlags;
        public void SetPlayerProfile(CallReducerFlags flags) => SetPlayerProfileFlags = flags;
    }
}
