// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateLastPositionLegacyHandler(ReducerEventContext ctx, DbVector3 position, float rotation);
        public event UpdateLastPositionLegacyHandler? OnUpdateLastPositionLegacy;

        public void UpdateLastPositionLegacy(DbVector3 position, float rotation)
        {
            conn.InternalCallReducer(new Reducer.UpdateLastPositionLegacy(position, rotation), this.SetCallReducerFlags.UpdateLastPositionLegacyFlags);
        }

        public bool InvokeUpdateLastPositionLegacy(ReducerEventContext ctx, Reducer.UpdateLastPositionLegacy args)
        {
            if (OnUpdateLastPositionLegacy == null) return false;
            OnUpdateLastPositionLegacy(
                ctx,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateLastPositionLegacy : Reducer, IReducerArgs
        {
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public float Rotation;

            public UpdateLastPositionLegacy(
                DbVector3 Position,
                float Rotation
            )
            {
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public UpdateLastPositionLegacy()
            {
                this.Position = new();
            }

            string IReducerArgs.ReducerName => "UpdateLastPositionLegacy";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateLastPositionLegacyFlags;
        public void UpdateLastPositionLegacy(CallReducerFlags flags) => UpdateLastPositionLegacyFlags = flags;
    }
}
